CREATE TABLE `est_enquiry` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Internal Record ID',
  `EnqID` varchar(20) NOT NULL COMMENT 'Auto Generated',
  `ICompanyID` varchar(10) NOT NULL,
  `ClientID` varchar(20) DEFAULT NULL COMMENT 'From companyMaster',
  `ExecutiveID` varchar(10) DEFAULT NULL COMMENT 'From EmployeeMaster',
  `Status` varchar(45) DEFAULT NULL COMMENT 'Pending/Estimated/Estimated & Quoted/Converted/Rejected',
  `IsActive` tinyint(1) DEFAULT NULL COMMENT 'Active or Deactive',
  `EnqDateTime` datetime DEFAULT NULL COMMENT 'Inq. Received Date',
  `ProductName` varchar(60) DEFAULT NULL,
  `ProductCode` varchar(45) DEFAULT NULL,
  `AnnualQty` double(12,1) NOT NULL DEFAULT '0.0',
  `Quantity` varchar(45) DEFAULT NULL COMMENT 'Can input multiple quantity',
  `Quantity2` varchar(45) DEFAULT NULL,
  `Quantity3` varchar(45) DEFAULT NULL,
  `Quantity4` varchar(45) DEFAULT NULL,
  `Quantity5` varchar(45) DEFAULT NULL,
  `PaperType` varchar(45) DEFAULT NULL COMMENT 'Select it from list or type',
  `Gsm` varchar(45) DEFAULT NULL COMMENT 'Select it from list or type',
  `ItemClass` varchar(45) DEFAULT NULL,
  `ItemType` varchar(45) DEFAULT NULL COMMENT 'List box for selecting carton from est_ItemTypeMaster',
  `Length` varchar(45) DEFAULT NULL,
  `Breadth` varchar(45) DEFAULT NULL,
  `Height` varchar(45) DEFAULT NULL,
  `Flap` varchar(45) DEFAULT NULL,
  `SidePast` varchar(45) DEFAULT NULL,
  `Ex1` varchar(45) DEFAULT NULL,
  `Ex2` varchar(45) DEFAULT NULL,
  `Ex3` varchar(45) DEFAULT NULL,
  `PrintColor` varchar(45) DEFAULT NULL COMMENT 'Drop down list or type it: 6 + 0; 5 + 0; 4 + 0; 3  + 0; 2 + 0; 1 + 0; 4 + 4',
  `PrePressDetail` varchar(500) DEFAULT NULL,
  `PressDetail` varchar(500) DEFAULT NULL,
  `PostPressDetail` varchar(500) DEFAULT NULL,
  `CorrugationDetail` varchar(500) DEFAULT NULL,
  `PackingDetail` varchar(100) DEFAULT NULL,
  `DespatchDetail` varchar(100) DEFAULT NULL,
  `OtherRemark` varchar(1000) DEFAULT NULL,
  `RecordID` varchar(10) DEFAULT NULL COMMENT 'RecordID of quotationnew table if estimate is made against it',
  `AUID` varchar(10) DEFAULT NULL,
  `ADateTime` datetime DEFAULT NULL,
  `MUID` varchar(10) DEFAULT NULL,
  `MDateTime` datetime DEFAULT NULL,
  `CostingDeptComment` varchar(200) DEFAULT NULL COMMENT 'Any comments given by costing department',
  `RecUpdateDateTime` datetime DEFAULT NULL COMMENT 'This record update by costing dep. datetime',
  `est_enquirycol` varchar(45) DEFAULT NULL,
  `ContactPerson` varchar(40) NOT NULL DEFAULT '',
  `PersonPost` varchar(40) NOT NULL DEFAULT '',
  `ContactNo_Email` varchar(50) NOT NULL DEFAULT '',
  `ModeOfInquiry` varchar(50) NOT NULL DEFAULT '',
  `ClientLocation` varchar(200) NOT NULL DEFAULT '',
  `est_purpose` int(3) NOT NULL DEFAULT '0' COMMENT 'Purpose of Enquiry',
  `Mill` varchar(150) NOT NULL DEFAULT '',
  `fp_detail` varchar(45) NOT NULL DEFAULT '',
  `ContactEmail` varchar(60) NOT NULL DEFAULT '',
  `NewClient` varchar(60) NOT NULL DEFAULT '',
  `ClientRemark` varchar(60) NOT NULL DEFAULT '',
  `papertype_remark` varchar(60) NOT NULL DEFAULT '',
  `Length_other` varchar(60) NOT NULL DEFAULT '',
  `Breadth_other` varchar(60) NOT NULL DEFAULT '',
  `Height_other` varchar(60) NOT NULL DEFAULT '',
  `Approved` tinyint(1) NOT NULL DEFAULT '0',
  `Reject` tinyint(1) NOT NULL,
  `Remark_approve` varchar(45) DEFAULT NULL,
  `Producttype` varchar(45) DEFAULT NULL,
  `delivery_date` varchar(50) DEFAULT NULL,
  `samplereference` varchar(100) DEFAULT NULL,
  `typeofproof` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`,`EnqID`,`ICompanyID`)
) ENGINE=InnoDB AUTO_INCREMENT=6554 DEFAULT CHARSET=latin1;



CREATE TABLE `est_enquiry_process` (
  `enqid` text,
  `enquiry_process_id` int(11) DEFAULT NULL,
  `printing` text,
  `printing_remarks` text,
  `coating` text,
  `coating_remarks` text,
  `lamination` text,
  `metpat_lamination` text,
  `lamination_remarks` text,
  `foiling` text,
  `foiling_remarks` text,
  `punching` text,
  `punching_remarks` text,
  `window_patching` text,
  `pasting` text,
  `pasting_remarks` text,
  `corrugation` text,
  `corrugation_remarks` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
